language: d
d: dmd-2.077

stages:
  - build
  - docker  

jobs:
  include:
    - stage: build
      name: "Build the project"
      script: 
        - dub build
    - stage: docker
      name: "Dockerize the app"
      script: 
        - docker build -t vibed-app .